# Site settings
title: "Brad Dougherty - Resume"
description: "Senior Production Engineer | Site Reliability Engineer | Tech Enthusiast"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Brad Dougherty"
resume_title:                   "Senior Production Engineer | Site Reliability Engineer"

# Contact Information
resume_contact_email:           "thisbrad@icloud.com"

# Hiding phone number, keeping location
resume_contact_address:         "Portland, OR"

# Header Contact Info Display
resume_header_contact_info:     "Portland, OR â€¢ thisbrad@icloud.com"
display_header_contact_info:    "true"

# Professional Summary
resume_header_intro: "<p>Experienced Production Engineer and Site Reliability Engineer with a passion for optimizing infrastructure, improving system reliability, and automating cloud deployments. Adept at leveraging DevOps best practices to enhance operational efficiency.</p>"

# Looking for Work Status
resume_looking_for_work:        "yes"

# Decide which sections to display
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
resume_social_links:
  resume_github_url:            "https://github.com/bradtaco"
  resume_linkedin_url:          "https://www.linkedin.com/in/brad-dougherty/"
  resume_website_url:           "https://brad-dougherty.com"

resume_print_social_links:      true

# Design settings
resume_theme:                   default